---
CLOUD_PUBLIC_HOST: fff
NAMESPACE: qubership-colly
MANAGED_BY: Helm
colly:
  global:
  envgeneInventoryService:
    image: ghcr.io/netcracker/envgene-inventory-service:1.0.0
    serviceName: envgene-inventory-service
    projectRepoUrl:
    projectRepoGitToken: fff
    gitTokens: [ ]
    # gitTokens:
    #   - region: cn
    #     token: ghp_token_for_cn
    #   - region: mb
    #     token: ghp_token_for_mb
    cronSchedule: 0 0/2 * * * ?
    cloudCoreSupport: false
    idp:
      url:
      clientId: envgene-inventory-service
      clientSecret:
    redis:
      hosts: redis://redis:6379
      username: ""
      password: ""
    ports:
      http: 8080
  environmentOperationalService:
    image: ghcr.io/netcracker/environment-operational-service:1.0.0
    serviceName: environment-operational-service
    cronSchedule: 0 0/1 * * * ?
    idp:
      url:
      clientId: environment-operational-service
      clientSecret:
    redis:
      hosts: redis://redis:6379
      username: ""
      password: ""
    sdPatterns:
      product: "(?i)product"
      project: "(?i)project"
    ports:
      http: 8080
    monitoring:
      - key: running-pods
        name: Running Pods
        query: count(kube_pod_status_phase{namespace=~"{namespace}",phase="Running"})
      - key: failed-deployments
        name: Failed Deployments
        query: count(kube_deployment_status_replicas_unavailable{namespace=~"{namespace}"})
  uiService:
    image: ghcr.io/netcracker/ui-service:latest
    serviceName: ui-service
    uiEnabled: false
    idp:
      url:
      clientId: ui-service
    ports:
      http: 8080
    ingress:
      className: alb
      http:
        annotations:
          alb.ingress.kubernetes.io/scheme: internet-facing
          alb.ingress.kubernetes.io/target-type: ip
