name: Build Project

on:
  workflow_dispatch: {}
permissions:
  packages: write

jobs:
  docker-check-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        component:
          - envgene-inventory-service
          - environment-operational-service
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build java
        uses: netcracker/qubership-workflow-hub/actions/maven-snapshot-deploy@feature/309-maven-snapshot-deploy
        with:
          java-version: 21
          maven-command: clean install
          working-directory: ${{ matrix.component }}
#      - name: Get version for current component
#        run: |
#          echo "IMAGE=${{ matrix.component }}" >> $GITHUB_ENV
#      - name: Docker build
#        uses: netcracker/qubership-workflow-hub/actions/docker-action@v1.0.4
#        with:
#          ref: ${{ github.ref }}
#          download-artifact: false
#          dry-run: true
#          component: ${{ toJson(matrix.component) }}
#        env:
#          GITHUB_TOKEN: ${{ github.token }}
